
[workspace]
members = [
    "ewf-core",
    "mock-module",
    "currencies",
    "websocket",
    "wallet-common",
    "prepare",
    "secret",
    "transaction",
    "tx-conn-udp",
    "history",
    "user"
]



